name: Build and Deploy

on:
  push:
    branches:
      - kobweb_latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main  # First checkout main branch

      - name: Fetch Latest Changes
        run: |
          git fetch origin kobweb_latest

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          git checkout kobweb_latest  # Switch to kobweb_latest to build
          ./gradlew clean
          ./gradlew :site:kobwebExport

      - name: Prepare and Push to Main
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Switch back to main branch
          git checkout main
          
          # Remove all files except .git and site
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name 'site' -exec rm -rf {} +
          
          # Copy the exported site content to root
          cp -r site/.kobweb/site/* .
          rm -rf site
          
          # Stage all changes
          git add -A
          
          # Create commit
          git commit -m "Update site from kobweb_latest"
          
          # Force push to main (use with caution!)
          git push --force origin main