name: Build and Deploy

on:
  push:
    branches:
      - kobweb_latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout kobweb_latest
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: kobweb_latest

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          ./gradlew clean
          ./gradlew :site:kobwebExport

      - name: Prepare and Push to Main
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Create a new orphan branch
          git checkout --orphan temp_branch
          
          # Remove all files from git tracking
          git rm -rf .
          
          # Create temporary directory for organizing files
          mkdir temp_dir
          
          # Copy only needed directories
          cp -r site/.kobweb/site/pages temp_dir/
          cp -r site/.kobweb/site/resources temp_dir/
          
          # Move system files to root level
          cp -r site/.kobweb/site/system/* temp_dir/
          
          # Clean up and move files to final position
          rm -rf *
          mv temp_dir/* .
          rm -rf temp_dir
          
          # Stage all changes
          git add -A
          
          # Create commit
          git commit -m "Update site from kobweb_latest v4"
          
          # Force push to main
          git push --force origin temp_branch:main
          
          # Clean up
          git checkout kobweb_latest
          git branch -D temp_branch